### PR TITLE
docs(API): Added API Versioning Process Documentation

### PR DESCRIPTION
**Pull request by alexflanagan**
## Overview

Define the process for API versioning and deprecation.

### Features

- add links and description to README.md
- create versioning-process.md to define the versioning and deprecation process.

#### Meta

- [x] provide a descriptive topic
- [x] provide an overview of contribution
- [x] no sensitive content included, such as:
  - security & privacy policy violating content
  - content considered competitive intelligence
  - keys, tokens or credentials
- [x] documentation format follows [this template][template]
- [x] fork is up to date ([see this guide from github](https://help.github.com/articles/syncing-a-fork/))
- [x] "work in progress" commits are squashed ([see "Squashing Commits"](https://git-scm.com/book/id/v2/Git-Tools-Rewriting-History))
- [x] commits follow the [Karma][karma-format] or [Commitizen](https://www.npmjs.com/package/commitizen) format

[template]: ../.template.md
[karma-format]: https://karma-runner.github.io/1.0/dev/git-commit-msg.html

### CODE REVIEW

**Comment by crimeminister** [comment]
Some discussion has taken place in Slack:

    I think I disagree with minor API versions being in the URL. In my experience in practice it’s not
    a great idea, as it requires you to maintain multiple processes and resources towards minor
    versions which are not breaking changes, especially when we get to the place where we’re doing
    routing at the gateway interface level. Also considering each branch becomes an independently
    maintained application, if you’re supporting every minor version as an accessible resource, you
    now are patching a potential magnitude of individual applications (branches)```

in reply:

    If I wanted to add a new key or endpoint to an API, in this case, would the docs still reflect that
    incremental change (ie. using semver), and how would I identify what version of the API I am now 
    consuming?

    Not requiring minor versions in the URI/request means you essentially have a "latest" endpoint
    (which I can't see us sanely stubbing out mock responses or contract tests against). If that is the
    way we want to go, then I would be inclined to use this "version" as more of a build number so
    that theres no difference between a major/minor update.

also:

    Have we considering something like this:
    https://github.com/paypal/api-standards/blob/master/api-style-guide.md#api-versioning
    
    This is a pretty practical approach to API application lifecycle development and management on 
    the web

    I do agree with the branching methodology though once we can manage that gracefully at the 
    network level

**Comment by tavogel** [comment]
We already have an API versioning standard, FWIW. There was an architecture break out session in early 2017. 

https://github.com/telusdigital/reference-architecture/blob/master/development/versioning.md#api-versioning

The idea was to use only major versions in the URL and custom version headers for anything else. There were several options for how to handle, that we didn't want to be prescriptive about. Either the one microservice handles all versions, or you can have old versions of the microservice running, or you can use the old microservice as lightweight wrapper for the new one.

**Comment by crimeminister** [comment]
As service meshes become a more prevalent way to manage routing, I see version-per-pod becoming preferred. That makes it easy to scale versions independently as well as take advantage of the more sophisticated routing capabilities these tools provide, while avoiding the need for services to implement that logic themselves. Ideally, this will contribute to keeping "micro" services micro and encourage a proliferation of narrow, do-one-thing-well APIs. It's probably not a bad idea to revisit some of our API architecture assumptions in light of the new capabilities things like Istio provide.

**Comment by anyuzer** [comment]
I agree with the Major version only in URL, and that we should move to per pod versioning once the network/routing support is there.

**Comment by tavogel** [comment]
Perhaps we need a short term strategy and a long term goal. Istio is not planned for OpenShift until Q3 next year at the earliest, so we'd probably need to migrate our entire API platform to GKE if we want to support it in the near future. We also need to revisit our strategy re: Authorization Proxy & API Gateways etc.

**Comment by crimeminister** [comment]
@tavogel Documenting our long term plans separately from current practice sounds like a good idea, particularly given the gateway work that's underway.

@alexflanagan We should add links between this and the existing versioning standard, ensure this change is aligned with the pre-existing standard, and use this as the place to provide more detailed discussion of API-related considerations and practice. This could also be the place to describe our longer-term goal and expectations around changes in practice as new technology and methodology change the API landscape, e.g. service mesh, GQL, RPC, ?.

**Comment by alexflanagan** [comment]
Too stale. Will resubmit after re-evaluation.

**Pull request closed without merging**
