### PR TITLE
feat(schema-validation): Add page describing schema validation of service responses in APIs

### PR DESCRIPTION
**Pull request by ethome**
## Overview

Several teams inside of Telus Digital have used ajv inside of APIs to validate responses of dependency services. This pattern seems to have been generally successful and reduced the pain of integrating with other services, so I wrote up a page outlining it. Let me know if you have any feedback!

### Features

- add schema validation page to API docs

---

#### Meta

- [x] provide a descriptive topic
- [x] provide an overview of contribution
- [x] no sensitive content included, such as:
  - security & privacy policy violating content
  - content considered competitive intelligence
  - keys, tokens or credentials
- [x] documentation format follows [this template][template]
- [x] fork is up to date ([see this guide from github](https://help.github.com/articles/syncing-a-fork/))
- [x] "work in progress" commits are squashed ([see "Squashing Commits"](https://git-scm.com/book/id/v2/Git-Tools-Rewriting-History))
- [x] commits follow the [Karma][karma-format] or [Commitizen](https://www.npmjs.com/package/commitizen) format

[template]: ../.template.md
[karma-format]: https://karma-runner.github.io/1.0/dev/git-commit-msg.html

### CODE REVIEW

**Comment by crimeminister** [comment]
This looks like a welcome addition. Would appreciate seeing some mention of the relationship between JSON Schema and Swagger given the increasing extent to which we rely on it for API description.

CC @alexflanagan

**Comment by crimeminister** [comment]
I like this pattern, my only hesitation lies in the fact that we'd like API developers to adopt Swagger/OpenAPI for the ancillary benefits it provides around documentation, discoverability, etc. In order to keep folks honest I would suggest that API responses be validated against the swagger definition of the API before being placed on the wire. There's no surer way in my experience to ensure that schemas accurately describe the responses being generated by a service. If that practice were widely adopted, would you still see value in doing more application-specific validation on the receiving side using JSON Schema / ajv?

**Comment by crimeminister** [comment]
@billxinli @mattseburn @tinyroy Hey gents, any feedback on this pattern?

**Comment by mattseburn** [comment]
@crimeminister I'm generally in favour of not adding unnecessary dependencies, so if this can be accomplished with a tool we're going to be using anyway I'd probably be more in favour of that.

**Comment by billxinli** [comment]
LGTM, I see many repos have `ajv` as a dependency, and it is a nice guard to detect upstream breaking API changes.

I'm curious to hear about strict vs non-strict validation with JSON schema/ajv. Also, can JSON schema/swagger definitions be flexible enough to accommodate a variety of JSON responses?

**Comment by crimeminister** [comment]
@billxinli Failing validation in the presence of data that is not described in a schema seems like a poor idea in the context of API development. It would cause unnecessary breakage in cases where functional behaviour is identical, e.g. an additive change to an API response that otherwise leaves the specified data intact; presumably schemas are used to validate the shape and presence of data that is explicitly required for a service to function, feature to be enabled, etc. That said, if there are cases where the assumption doesn't bear weight we should call them out. As for these validation mechanisms being sufficiently flexible, I think that the breadth of usage they're already seeing suggests that we aren't encountering any practical difficulties in that way.

**Pull request merged**
