### PR TITLE
feat(css): Expand on CSS reference

### PR DESCRIPTION
**Pull request by ryanoglesby08**
## Overview

Focus on best practices around scoping styles and co-locating styles with components. Add more detail to the CSS doc.

### CODE REVIEW

**Comment by tsungting** [comment]
I like the 'styled component' pattern here because it allows the component css to be scoped and not be affected by unintentional changes meant for other components.  However I find coding css styles directly into the components to be a little too low level and sometimes don't convey the intention for that style very well.  eg.

```
style = {
    font-size: 12px
}
```

This tells me the font size is 12px, but what I actually want to know may be if this font-size is small, medium or large when compared to fonts of other text on the page.  In other words this gives me information about the style of the component, but outside of context of the entire page.

Designers I respect use libraries/css naming such as http://basscss.com/ to style on the component level, while at the same time creating readability and context to describe the look of the component.  For example if I see an element with classes

```
<span class="h6 underline red left-border">
```

I can guess easily that this is normal text, but it should have the size of h6, be underlined, coloured red, and have left border showing.

Thoughts?

**Comment by crimeminister** [comment]
@quirkles @githubjosh Anything to add re this PR?

**Comment by quirkles** [comment]
I like it, I have no objections at all to the approach. My only concern is that without enforcement it just wont happen. There are teams who still don't use the telus digital linter, so telling them they need to write their styles this way probably wont have much of an effect. Given that most teams already have a product with a bunch of (more or less) modular stylesheets, is the purpose of this document to give people a platonic ideal to aim at when refactoring their code?

Another question is how do you ensure there is buy-in from teams? Ive no intention of calling anybody or team out but most of the code I've seen here is in line with only a pretty small subset of the (very sensible and impressive) RA guidelines and even then to varying degrees. I don't know how much of that is the RA guidelines evolving as the products are being written or people not being cognizant this repo exists, or people knowing it exists and just doing whatever they want anyway.

So I guess in summary: I think that this method is a very sensible way of organizing style-related code but I also think that a lot of teams already ignore a lot of very sensible suggestions here.

**Comment by ryanoglesby08** [comment]
>  is the purpose of this document to give people a platonic ideal to aim at when refactoring their code?

Yes, that was my intention, at least for a start. I figured it was best to start by laying out principles in a public way, giving it time to spread, and getting feedback. So far, when we have discussed this kind of stuff at arch forum, everyone in attendance seemed to generally agree with the things we have been saying. There are also teams already doing modular CSS and using CSS-in-JS, so seems like these principles are already being adopted by some pioneers. I think it takes a long time to change culture, so I view this article as one piece in a larger effort to do that.

> My only concern is that without enforcement it just wont happen.

Agreed. Enforcement is hard. This article can serve to explain underlying principles and ideals. We can then augment it by providing tools and configuration such as adding CSS modules to the starter kit. Eventually we could be testing for the adherence to modular CSS or something.

> So I guess in summary: I think that this method is a very sensible way of organizing style-related code but I also think that a lot of teams already ignore a lot of very sensible suggestions here.

This seems like something to bring up as a more meta point around the reference architecture wiki. I'm not sure if it's meant to be just that, a _reference_, or more of a rule of law.

**Comment by tsungting** [comment]
Yeah, what you said makes sense to me.  Mainly I think it's useful to read the code and 

1.  Get a context of why the border is 8px as opposed to 9 or 7.
2.  Be able to copy and paste the code and change the parts that's different without creating a pain later when border thickness is changed from 8px to 13px for the whole project.

```
import { small, underline } from “./styles/fonts"
import { brandRed } from “./styles/colours”
import { thin } from “./styles/borders”

style = {
  fontSize: small,
  textDecoration: underline
  border: `${thin} solid ${brandRed}`
}
```

Fulfills both wishes, so I am onboard with that.

**Comment by crimeminister** [comment]
Thanks for the contribution @ryanoglesby08!

**Pull request merged**
