### PR TITLE
add security checklist staring point

### PR DESCRIPTION
**Pull request by ahmadnassri**
### Outline

Describe the overview of your changes

###### Check List

- [ ] commits are squashed 
- [ ] commits follow the [Karma format][karma-format]

[karma-format]: karma-runner.github.io/1.0/dev/git-commit-msg.html

### CODE REVIEW

**Comment by ahmadnassri** [comment]
@Deep-Six are you going to be able to provide some refactoring and structure on this? or should we close it off?

**Comment by crimeminister** [comment]
@Deep-Six @WITMiddle @ahmadnassri there's a fair amount of overlap with the recent PRs sent by @WITMiddle. Is there value in having a top-level pre-flight checklist that links out to the various documents that are being proposed for inclusion?

**Comment by WITMiddle** [comment]
@crimeminister - I'm in process of integrating my security standards content that live in a g doc into github. I have broken down into separate sections, each having separate PR to make the review process more easier. I still have quite a bit of sections to add as PR, but going through a bit of a learning curve here as this is first time I'm using github to contribute - thank you for bearing with me. So, my structure is as such: created "security-standards" branch off of master, and will have separate PR as separate branches off of this branch

**Comment by WITMiddle** [comment]
Continued: 
My structure is as such: created "security-standards" branch off of master (will contain the top level README.md) , and will have separate sections as separate PR as separate branches off of this branch. I suggest waiting until all of my content is in as PRs prior to deciding if we wanted to merge with any other content.

**Comment by crimeminister** [comment]
Since this is a living document, feel free to propose smaller changes and update frequently! It might make the process easier. And do let me know if I can help out in any way.

**Comment by crimeminister** [comment]
@WITMiddle After thinking on it for a bit, I feel as though I'd really like to see a security-related checklist included as a convenient reference. I realize you'll very likely want to fine-tune it as you work on your contributions, though. I'll merge as-is; please feel free to update it as part of your ongoing efforts.

**Pull request merged**
