### PR TITLE
refactor(index): bring back the index page

### PR DESCRIPTION
**Pull request by tavogel**
## Overview

Reference architecture wiki should let you see the core RA technologies & traditions at-a-glance, so that it can be used as a tech radar & instructional repo. With the sections buried, and many concerns overlapping, its hard to know where to look.

I have left out the testing section as it has heavily strayed from the original index.

### Features

Move decentralized indices back to the root of the project

#### Meta

- [x] provide a descriptive topic
- [x] provide an overview of contribution
- [x] no sensitive content included, such as:
  - security & privacy policy violating content
  - content considered competitive intelligence
  - keys, tokens or credentials
- [x] documentation format follows [this template][template]
- [x] fork is up to date ([see this guide from github](https://help.github.com/articles/syncing-a-fork/))
- [x] "work in progress" commits are squashed ([see "Squashing Commits"](https://git-scm.com/book/id/v2/Git-Tools-Rewriting-History))
- [x commits follow the [Karma][karma-format] or [Commitizen](https://www.npmjs.com/package/commitizen) format

[template]: ../.template.md
[karma-format]: https://karma-runner.github.io/1.0/dev/git-commit-msg.html

### CODE REVIEW

**Comment by tavogel** [comment]
¯\_(ツ)_/¯

**Comment by crimeminister** [comment]
@ahmadnassri Any thoughts on how we want to lay out the index for RA?

**Comment by ahmadnassri** [comment]
@crimeminister @tavogel waiting on HALO progress before we tackle this again, as it will need to reflect on the web site as well

**Comment by tavogel** [comment]
As a QOL improvement I would recommend at least linking to the anchor for the readme (or to the readme file itself). E.g. when you click on Development you have to scroll all the way down to resume browsing the index.

**Comment by ahmadnassri** [comment]
to quote @tavogel: "I welcome your pull request" 😉

**Comment by tavogel** [comment]
He says from his ivory tower in Aruba, in the corpse my abandoned pull request :trollface: 

https://github.com/telusdigital/reference-architecture/pull/97 🤣

**Pull request closed without merging**
